### ISSUE TITLE
Unable to Start Server after 1.12 update - RFTools Crash

### ISSUE THREAD

**Issue by jsb305** [Iskallia/Vault-public#669]
**Describe the bug**
When my server attempts to start after updating to 1.12 RFTools crashes and prevents server startup.

**To Reproduce**
1. Update server to 1.12
2. Start Server
3.
4.

**Expected behavior**

**Screenshots or Crash Report**
[11.01 14:54:40] [Server] -- MOD rftoolsutility --
[11.01 14:54:40] [Server] Details:
[11.01 14:54:40] [Server] 	Mod Filerftoolsutility-1.16-3.1.7.jar
[11.01 14:54:40] [Server] 	Failure messageRFToolsUtility (rftoolsutility) encountered an error during the load_registries event phase
[11.01 14:54:40] [Server] 		java.lang.NoSuchMethodErrormcjty.lib.container.GenericContainer.createRemoteContainerType(Ljava/util/function/Function;Lmcjty/lib/varia/TriFunction;I)Lnet/minecraft/inventory/container/ContainerType;
[11.01 14:54:40] [Server] 	Mod Version1.16-3.1.7
[11.01 14:54:40] [Server] 	Mod Issue URLhttp://github.com/McJtyMods/RFToolsUtility/issues
[11.01 14:54:40] [Server] 	Exception messagejava.lang.NoSuchMethodError: mcjty.lib.container.GenericContainer.createRemoteContainerType(Ljava/util/function/Function;Lmcjty/lib/varia/TriFunction;I)Lnet/minecraft/inventory/container/ContainerType;
[11.01 14:54:40] [Server] Stacktrace:
[11.01 14:54:40] [Server] 	at mcjty.rftoolsutility.modules.screen.ScreenModule.lambda$static$6(ScreenModule.java:36) ~[rftoolsutility:1.16-3.1.{re:classloading}
[11.01 14:54:40] [Server] 	at net.minecraftforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:124) ~[forge:?] {re:classloading}
[11.01 14:54:40] [Server] 	at net.minecraftforge.registries.DeferredRegister.addEntries(DeferredRegister.java:200) ~[forge:?] {re:classloading}
[11.01 14:54:40] [Server] 	at net.minecraftforge.registries.DeferredRegister.access$000(DeferredRegister.java:61) ~[forge:?] {re:classloading}

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version 1.7.0p1.12.1

**Additional context**
